= OpenLDAP demo container

OpenLDAP Docker container for demo purposes.

Based on https://github.com/osixia/docker-openldap[osixia/docker-openldap].

== Use case

Occasionally I have a need to have LDAP server with groups and users. That's why this image exists. No installations, no setup, just run and use.

== Usage

* Get Docker image:
```
docker pull kazhar/openldap-demo
```
* Run Docker image: 
```
docker run -d -p 389:389 -p 636:636 --name openldap-demo kazhar/openldap-demo
```
* Login to server:
** Base DN: `dc=sirius,dc=com`
** Admin user: `cn=admin,dc=sirius,dc=com`
** Password: `passw0rd`

Or you can download/clone this repo and create and build your own OpenLDAP image.

== Groups and users

Groups and users are specified in link:config.ini[config.ini]-file. When building container, LDIF file is generated (much like link:sample.ldif[sample.ldif]).

One group is:

- `cn=admin,ou=groups,dc=sirius,dc=com`

And one user in that group is :

- `uid=kdoyle,ou=users,dc=sirius,dc=com`

The default password for all users is `passw0rd`. Another password can be set in link:config.ini[config.ini].

See the generated LDIF or use a LDAP admin tool to get more information about the user entries.

== LDAP connection and filters

Some applications ask for LDAP connection and filters. If using the default OpenLDAP demo image, here are the settings and filters that should work:

|===
|Setting |Value

|URL
|`ldap://server.ip:389`

|Base DN
|`dc=sirius,dc=com`

|Bind DN
|`cn=admin,dc=sirius,dc=com`

|Admin password
|`passw0rd`

|User filter
|`(&(uid=%v)(objectclass=inetOrgPerson))`

|Group filter
|`(&(cn=%v)(objectclass=groupOfUniqueNames))`

|Group member ID map 
|`groupOfUniqueNames:uniqueMember`

|User ID map
|`*:uid`

|Group ID map
|`*:cn`

|===

== Create your own demo image

In order to create your own OpenLDAP image with custom domain and users, edit link:config.ini[config.ini] and then build a new OpenLDAP image.

* Edit link:config.ini[config.ini].
* Build image:
```
docker build -t my-openldap .
```
* Start:
```
docker run -it --rm -p 389:389 -p 636:636 --name my-openldap my-openldap
```

=== config.ini

link:config.ini[config.ini] include settings like organization name, domain and users/groups. Modify them as required.

link:config.ini[config.ini] includes also key `useRandomOrganizationAndUsers`. If the values is `yes`, random organization and users are created when building the container.

In order to view generated organization and users, the build process adds _config.ini_ and _settings.txt_ files to the root of container filesystem.

* View _settings.txt_, including base DN, bind DN and filters:
```
docker exec my-openldap cat /settings.txt
```
* View _generated.ldif_, including users and passwords:
```
docker exec my-openldap cat /generated.ldif
```
* View _config.ini_, used to build the image:
```
docker exec my-openldap cat /config.ini
```

== Scripts

link:scripts/[scripts]-directory includes some scripts that can be used to search LDAP by userid, last name, package files for offline distribution and others.


